<a href="https://colab.research.google.com/github/Harika-25888/Harika-25888/blob/%40Harika/Bitcoin_Price_Prediction_Using_ML_Code_Executed.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np
import math
import datetime as dt
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error, mean_absolute_error, explained_variance_score, r2_score
from sklearn.metrics import mean_poisson_deviance, mean_gamma_deviance, accuracy_score
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
from itertools import cycle
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots

Mounted at /content/drive

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
import os
import pandas as pd
import numpy as np
import math
import datetime as dt
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error, mean_absolute_error, explained_variance_score, r2_score
from sklearn.metrics import mean_poisson_deviance, mean_gamma_deviance, accuracy_score
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
from itertools import cycle
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots

In [4]:
maindf = pd.read_csv('/content/Binance_1INCHBTC_d.csv')

In [5]:
print('Total number of days present in the dataset: ',maindf.shape[0])
print('Total number of fields present in the dataset: ',maindf.shape[1])

Total number of days present in the dataset:  1469
Total number of fields present in the dataset:  1

In [6]:
maindf.head()

                                                                                              https://www.CryptoDataDownload.com
Unix          Date       Symbol   Open     High     Low      Close    Volume 1INCH Volume BTC                         tradecount
1735603200000 2024-12-31 1INCHBTC 4.22e-06 4.22e-06 4.08e-06 4.09e-06 164928.3     0.68439102                                415
1735516800000 2024-12-30 1INCHBTC 4.18e-06 4.32e-06 4.13e-06 4.23e-06 210753.3     0.88699683                                832
1735430400000 2024-12-29 1INCHBTC 4.32e-06 4.32e-06 4.16e-06 4.19e-06 77095.2      0.32491404                                327
1735344000000 2024-12-28 1INCHBTC 4.14e-06 4.34e-06 4.14e-06 4.33e-06 87745.4      0.37170515                                543

In [7]:
maindf.shape

(1469, 1)

In [8]:
maindf.tail()

                                                                                                   https://www.CryptoDataDownload.com
1609200000000 2020-12-29 1INCHBTC 4.118e-05 4.123e-05 2.868e-05 3.236e-05 11666843.3 391.16343032                               48704
1609113600000 2020-12-28 1INCHBTC 4.028e-05 4.72e-05  3.952e-05 4.117e-05 9797253.1  421.12551535                               42828
1609027200000 2020-12-27 1INCHBTC 6.029e-05 6.222e-05 3.921e-05 4.034e-05 18382333.9 883.26023123                               83251
1608940800000 2020-12-26 1INCHBTC 9.289e-05 9.999e-05 6.005e-05 6.021e-05 16588695.5 1215.78288975                              93597
1608854400000 2020-12-25 1INCHBTC 8.51e-06  0.000168  8.51e-06  9.319e-05 31915447.1 3145.36703942                             226447

In [9]:
maindf.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1469 entries, ('Unix', 'Date', 'Symbol', 'Open', 'High', 'Low', 'Close', 'Volume 1INCH', 'Volume BTC') to ('1608854400000', '2020-12-25', '1INCHBTC', '8.51e-06', '0.000168', '8.51e-06', '9.319e-05', '31915447.1', '3145.36703942')
Data columns (total 1 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   https://www.CryptoDataDownload.com  1469 non-null   object
dtypes: object(1)
memory usage: 377.9+ KB

In [10]:
maindf.describe()

       https://www.CryptoDataDownload.com
count                                1469
unique                               1359
top                                  2343
freq                                    4

In [11]:
print('Null Values:',maindf.isnull().values.sum())
print('NA values:',maindf.isnull().values.any())

Null Values: 0
NA values: False

In [12]:
maindf.shape

(1469, 1)

In [13]:
sd=maindf.iloc[0][0]
ed=maindf.iloc[-1][0]
print('Starting Date',sd)
print('Ending Date',ed)

Starting Date tradecount
Ending Date 226447

<ipython-input-13-a348cfd11536>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  sd=maindf.iloc[0][0]
<ipython-input-13-a348cfd11536>:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ed=maindf.iloc[-1][0]

In [14]:
print(maindf.columns)

Index(['https://www.CryptoDataDownload.com'], dtype='object')

In [15]:
maindf.rename(columns=lambda x: x.strip(), inplace=True)
maindf.rename(columns=str.lower, inplace=True)

In [16]:
import pandas as pd

# Load data
url = '/content/Binance_1INCHBTC_d.csv'  # Update this to the actual URL of your CSV file
maindf = pd.read_csv(url)

# Check column names and structure
print(maindf.columns)
print(maindf.head())

# Ensure the 'Date' column exists and is correctly named
if 'Date' in maindf.columns:
    maindf['Date'] = pd.to_datetime(maindf['Date'], format='%d-%m-%Y')
    y_overall = maindf.loc[(maindf['Date'] >= '2014-09-17') & (maindf['Date'] <= '2022-02-19')]
    y_overall.drop(['Adj Close', 'Volume'], axis=1, inplace=True)
else:
    print("The 'Date' column does not exist in the DataFrame.")

Index(['https://www.CryptoDataDownload.com'], dtype='object')
                                                                                              https://www.CryptoDataDownload.com
Unix          Date       Symbol   Open     High     Low      Close    Volume 1INCH Volume BTC                         tradecount
1735603200000 2024-12-31 1INCHBTC 4.22e-06 4.22e-06 4.08e-06 4.09e-06 164928.3     0.68439102                                415
1735516800000 2024-12-30 1INCHBTC 4.18e-06 4.32e-06 4.13e-06 4.23e-06 210753.3     0.88699683                                832
1735430400000 2024-12-29 1INCHBTC 4.32e-06 4.32e-06 4.16e-06 4.19e-06 77095.2      0.32491404                                327
1735344000000 2024-12-28 1INCHBTC 4.14e-06 4.34e-06 4.14e-06 4.33e-06 87745.4      0.37170515                                543
The 'Date' column does not exist in the DataFrame.

In [17]:
print(maindf.columns)

Index(['https://www.CryptoDataDownload.com'], dtype='object')

In [18]:
print(maindf.head())

                                                                                              https://www.CryptoDataDownload.com
Unix          Date       Symbol   Open     High     Low      Close    Volume 1INCH Volume BTC                         tradecount
1735603200000 2024-12-31 1INCHBTC 4.22e-06 4.22e-06 4.08e-06 4.09e-06 164928.3     0.68439102                                415
1735516800000 2024-12-30 1INCHBTC 4.18e-06 4.32e-06 4.13e-06 4.23e-06 210753.3     0.88699683                                832
1735430400000 2024-12-29 1INCHBTC 4.32e-06 4.32e-06 4.16e-06 4.19e-06 77095.2      0.32491404                                327
1735344000000 2024-12-28 1INCHBTC 4.14e-06 4.34e-06 4.14e-06 4.33e-06 87745.4      0.37170515                                543

In [19]:
import pandas as pd

# Load data with proper delimiters and skip the first row if it's just metadata
url = '/content/Binance_1INCHBTC_d.csv'
maindf = pd.read_csv(url, skiprows=1)

# Check column names and structure
print(maindf.columns)
print(maindf.head())

# Rename columns if necessary
maindf.columns = ['Unix', 'Date', 'Symbol', 'Open', 'High', 'Low', 'Close', 'Volume 1INCH', 'Volume BUSD', 'tradecount']

# Drop unnecessary columns
maindf.drop(['Volume 1INCH', 'Volume BUSD', 'tradecount'], axis=1, inplace=True)

# Ensure the 'Date' column exists and is correctly named
if 'Date' in maindf.columns:
    maindf['Date'] = pd.to_datetime(maindf['Date'], format='%Y-%m-%d')
    y_overall = maindf.loc[(maindf['Date'] >= '2022-12-28') & (maindf['Date'] <= '2023-04-01')]
    print(y_overall.head())
else:
  print("The 'Date' column does not exist in the DataFrame.")

Index(['Unix', 'Date', 'Symbol', 'Open', 'High', 'Low', 'Close',
       'Volume 1INCH', 'Volume BTC', 'tradecount'],
      dtype='object')
            Unix        Date    Symbol      Open      High       Low  \
0  1735603200000  2024-12-31  1INCHBTC  0.000004  0.000004  0.000004
1  1735516800000  2024-12-30  1INCHBTC  0.000004  0.000004  0.000004
2  1735430400000  2024-12-29  1INCHBTC  0.000004  0.000004  0.000004
3  1735344000000  2024-12-28  1INCHBTC  0.000004  0.000004  0.000004
4  1735257600000  2024-12-27  1INCHBTC  0.000004  0.000004  0.000004

      Close  Volume 1INCH  Volume BTC  tradecount
0  0.000004      164928.3    0.684391         415
1  0.000004      210753.3    0.886997         832
2  0.000004       77095.2    0.324914         327
3  0.000004       87745.4    0.371705         543
4  0.000004       90503.4    0.375294         419
              Unix       Date    Symbol      Open      High       Low  \
640  1680307200000 2023-04-01  1INCHBTC  0.000020  0.000020  0.000019
641  1680220800000 2023-03-31  1INCHBTC  0.000020  0.000020  0.000019
642  1680134400000 2023-03-30  1INCHBTC  0.000018  0.000021  0.000018
643  1680048000000 2023-03-29  1INCHBTC  0.000018  0.000018  0.000018
644  1679961600000 2023-03-28  1INCHBTC  0.000018  0.000019  0.000018

        Close
640  0.000019
641  0.000020
642  0.000020
643  0.000018
644  0.000018

In [20]:
import pandas as pd

# Load data, skipping the first row if it's metadata
url = '/content/Binance_1INCHBTC_d.csv'
maindf = pd.read_csv(url, skiprows=1)

# Check column names and structure
print("Columns in the DataFrame:", maindf.columns)
print(maindf.head())

# Rename columns if necessary
maindf.rename(columns={
    'Volume BUSD': 'Volume',
    'Close': 'Adj Close'
}, inplace=True)

# Ensure the 'Date' column exists and is correctly formatted
if 'Date' in maindf.columns:
    try:
        maindf['Date'] = pd.to_datetime(maindf['Date'], format='%Y-%m-%d')
        # Filter rows based on the Date range
        y_overall = maindf[(maindf['Date'] >= '2022-12-28') & (maindf['Date'] <= '2023-04-01')]
        # Drop specified columns
        y_overall = y_overall.drop(['Adj Close', 'Volume'], axis=1, errors='ignore')
        print(y_overall.head())
    except Exception as e:
        print(f"Error processing 'Date' column: {e}")
else:
    print("The 'Date' column does not exist in the DataFrame.")

Columns in the DataFrame: Index(['Unix', 'Date', 'Symbol', 'Open', 'High', 'Low', 'Close',
       'Volume 1INCH', 'Volume BTC', 'tradecount'],
      dtype='object')
            Unix        Date    Symbol      Open      High       Low  \
0  1735603200000  2024-12-31  1INCHBTC  0.000004  0.000004  0.000004
1  1735516800000  2024-12-30  1INCHBTC  0.000004  0.000004  0.000004
2  1735430400000  2024-12-29  1INCHBTC  0.000004  0.000004  0.000004
3  1735344000000  2024-12-28  1INCHBTC  0.000004  0.000004  0.000004
4  1735257600000  2024-12-27  1INCHBTC  0.000004  0.000004  0.000004

      Close  Volume 1INCH  Volume BTC  tradecount
0  0.000004      164928.3    0.684391         415
1  0.000004      210753.3    0.886997         832
2  0.000004       77095.2    0.324914         327
3  0.000004       87745.4    0.371705         543
4  0.000004       90503.4    0.375294         419
              Unix       Date    Symbol      Open      High       Low  \
640  1680307200000 2023-04-01  1INCHBTC  0.000020  0.000020  0.000019
641  1680220800000 2023-03-31  1INCHBTC  0.000020  0.000020  0.000019
642  1680134400000 2023-03-30  1INCHBTC  0.000018  0.000021  0.000018
643  1680048000000 2023-03-29  1INCHBTC  0.000018  0.000018  0.000018
644  1679961600000 2023-03-28  1INCHBTC  0.000018  0.000019  0.000018

     Volume 1INCH  Volume BTC  tradecount
640      487048.6    9.385661        2340
641     1080340.2   21.162852        4179
642     3636421.4   72.167839       14366
643      694808.7   12.605093        3818
644      634484.7   11.602980        4300

In [21]:
import pandas as pd

# Load data, skipping the first row if it's metadata
url = '/content/Binance_1INCHBTC_d.csv'
maindf = pd.read_csv(url, skiprows=1)

# Check column names and structure
print("Columns in the DataFrame:", maindf.columns)
print(maindf.head())

# Rename columns for consistency
maindf.rename(columns={
    'Volume BUSD': 'Volume',
    'Close': 'Close'
}, inplace=True)

# Ensure the 'Date' column exists and is correctly formatted
if 'Date' in maindf.columns:
    try:
        # Convert 'Date' to datetime format
        maindf['Date'] = pd.to_datetime(maindf['Date'], format='%Y-%m-%d')

        # Filter rows based on the specified Date range
        y_overall = maindf[(maindf['Date'] >= '2022-12-28') & (maindf['Date'] <= '2023-04-01')]

        # Drop the 'Volume' column
        y_overall = y_overall.drop(['Volume'], axis=1)

        # Group by month and calculate mean of 'Open' and 'Close'
        monthvise = y_overall.groupby(y_overall['Date'].dt.strftime('%B'))[['Open', 'Close']].mean()

        # Reorder months for proper chronological order
        new_order = ['January', 'February', 'March', 'April', 'May', 'June',
                     'July', 'August', 'September', 'October', 'November', 'December']
        monthvise = monthvise.reindex(new_order).dropna(how='all')  # Drop rows for missing months
        print(monthvise)
    except Exception as e:
      print(f"Error processing the DataFrame: {e}")
else:
    print("The 'Date' column does not exist in the DataFrame.")

Columns in the DataFrame: Index(['Unix', 'Date', 'Symbol', 'Open', 'High', 'Low', 'Close',
       'Volume 1INCH', 'Volume BTC', 'tradecount'],
      dtype='object')
            Unix        Date    Symbol      Open      High       Low  \
0  1735603200000  2024-12-31  1INCHBTC  0.000004  0.000004  0.000004
1  1735516800000  2024-12-30  1INCHBTC  0.000004  0.000004  0.000004
2  1735430400000  2024-12-29  1INCHBTC  0.000004  0.000004  0.000004
3  1735344000000  2024-12-28  1INCHBTC  0.000004  0.000004  0.000004
4  1735257600000  2024-12-27  1INCHBTC  0.000004  0.000004  0.000004

      Close  Volume 1INCH  Volume BTC  tradecount
0  0.000004      164928.3    0.684391         415
1  0.000004      210753.3    0.886997         832
2  0.000004       77095.2    0.324914         327
3  0.000004       87745.4    0.371705         543
4  0.000004       90503.4    0.375294         419
Error processing the DataFrame: "['Volume'] not found in axis"

In [22]:
names = cycle(['Stock Open Price','Stock Close Price','Stock High Price','Stock Low Price'])
fig = px.line(y_overall, x=y_overall.Date, y=[y_overall['Open'], y_overall['Close'],
y_overall['High'], y_overall['Low']],
labels={'Date': 'Date','value':'Stock value'})
fig.update_layout(title_text='Stock analysis chart', font_size=15, font_color='black',legend_title_text='Stock Parameters')
fig.for_each_trace(lambda t: t.update(name = next(names)))
fig.update_xaxes(showgrid=False)
fig.update_yaxes(showgrid=False)

# New Section

In [23]:
closedf = maindf[['Date','Close']]
print("Shape of close dataframe:",closedf.shape)

Shape of close dataframe: (1468, 2)

In [24]:
fig = px.line(closedf, x=closedf.Date, y=closedf.Close,labels={'date':'Date','close':'Close Stock'})
fig.update_traces(marker_line_width=2, opacity=0.8, marker_line_color='orange')
fig.update_layout(title_text='Whole period of timeframe of Bitcoin close price 2014-2024', plot_bgcolor='white',
font_size=15, font_color='black')
fig.update_xaxes(showgrid=False)
fig.update_yaxes(showgrid=False)
fig.show()

In [25]:
closedf = closedf[closedf['Date'] > '2021-02-19']
close_stock = closedf.copy()
print("Total data for prediction: ",closedf.shape[0])

Total data for prediction:  1411

In [26]:
closedf

           Date     Close
0    2024-12-31  0.000004
1    2024-12-30  0.000004
2    2024-12-29  0.000004
3    2024-12-28  0.000004
4    2024-12-27  0.000004
...         ...       ...
1406 2021-02-24  0.000073
1407 2021-02-23  0.000076
1408 2021-02-22  0.000084
1409 2021-02-21  0.000088
1410 2021-02-20  0.000092

[1411 rows x 2 columns]

In [27]:
fig = px.line(closedf, x=closedf.Date, y=closedf.Close,labels={'date':'Date','close':'Close Stock'})
fig.update_traces(marker_line_width=2, opacity=0.8, marker_line_color='orange')
fig.update_layout(title_text='Considered period to predict Bitcoin close price',
plot_bgcolor='white', font_size=15, font_color='black')
fig.update_xaxes(showgrid=False)
fig.update_yaxes(showgrid=False)
fig.show()

In [28]:
del closedf['Date']
scaler=MinMaxScaler(feature_range=(0,1))
closedf=scaler.fit_transform(np.array(closedf).reshape(-1,1))
print(closedf.shape)

(1411, 1)

In [29]:
training_size=int(len(closedf)*0.60)
test_size=len(closedf)-training_size
train_data,test_data=closedf[0:training_size,:],closedf[training_size:len(closedf),:1]
print("train_data: ", train_data.shape)
print("test_data: ", test_data.shape)

train_data:  (846, 1)
test_data:  (565, 1)

In [30]:
import numpy as np

def create_dataset(dataset, time_step=1):
    dataX, dataY = [], []
    for i in range(len(dataset) - time_step - 1):
        a = dataset[i:(i + time_step), 0]  # i=0, 0,1,2,3,...,99 100
        dataX.append(a)
        dataY.append(dataset[i + time_step, 0])
    return np.array(dataX),np.array(dataY)

In [31]:
time_step = 15
X_train, y_train = create_dataset(train_data, time_step)
X_test, y_test = create_dataset(test_data, time_step)
print("X_train: ", X_train.shape)
print("y_train: ", y_train.shape)
print("X_test: ", X_test.shape)
print("y_test",y_test.shape)

X_train:  (830, 15)
y_train:  (830,)
X_test:  (549, 15)
y_test (549,)

In [32]:
X_train =X_train.reshape(X_train.shape[0],X_train.shape[1] , 1)
X_test = X_test.reshape(X_test.shape[0],X_test.shape[1] , 1)
print("X_train: ", X_train.shape)
print("X_test: ",X_test.shape)

X_train:  (830, 15, 1)
X_test:  (549, 15, 1)

In [33]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).